name: Publish artifacts
on:
  release:
    types: [created]
jobs:
  publish-npm:
    name: Build and publish to NPM
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: js
    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - uses: JS-DevTools/npm-publish@v1
        with:
          package: js/package.json
          token: ${{ secrets.NPM_TOKEN }}
  publish-maven:
    name: Build and publish to Maven Repository
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kotlin
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"
      - name: Release build
        run: ./gradlew build
      - name: Publish to MavenCentral
        run: ./gradlew publishAllPublicationToSonatypeRepository --max-workers 1 closeAndReleaseSonatypeStagingRepository
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_SIGNING_KEY: ${{ secrets.SIGNING_SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
